// <auto-generated />
using EgyptTour.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTour.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510135519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptTour.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tours",
                            Description = "Experience the ancient wonders of Egypt with our guided tour of the Pyramids of Giza.",
                            ImageUrl = "/images/pyramids.jpg",
                            Name = "Pyramids Tour",
                            Price = 99.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cruises",
                            Description = "Enjoy a luxurious cruise along the Nile River with stunning views and cultural experiences.",
                            ImageUrl = "/images/nile-cruise.jpg",
                            Name = "Nile Cruise",
                            Price = 299.99m,
                            StockQuantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
