// <auto-generated />
using EgyptTour.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTour.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510140802_AddMoreProducts")]
    partial class AddMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptTour.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tours",
                            Description = "Experience the ancient wonders of Egypt with our guided tour of the Pyramids of Giza.",
                            ImageUrl = "/images/pyramids.jpg",
                            Name = "Pyramids Tour",
                            Price = 99.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cruises",
                            Description = "Enjoy a luxurious cruise along the Nile River with stunning views and cultural experiences.",
                            ImageUrl = "/images/nile-cruise.jpg",
                            Name = "Nile Cruise",
                            Price = 299.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Artwork",
                            Description = "Authentic Egyptian papyrus paintings with ancient motifs.",
                            ImageUrl = "https://images.unsplash.com/photo-1565992441121-4367c2967103",
                            Name = "Handcrafted Papyrus Art",
                            Price = 45m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Category = "Souvenirs",
                            Description = "Hand-carved replicas of famous Egyptian deities.",
                            ImageUrl = "https://images.unsplash.com/photo-1598188306155-25e8eb807948",
                            Name = "Alabaster Statues",
                            Price = 120m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = "Jewelry",
                            Description = "Inspired by ancient Egyptian designs with modern craftsmanship.",
                            ImageUrl = "https://images.unsplash.com/photo-1611591437281-460bfbe1220a",
                            Name = "Gold-Plated Jewelry",
                            Price = 85m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 6,
                            Category = "Beauty",
                            Description = "Traditional Egyptian scents like lotus and amber.",
                            ImageUrl = "https://images.unsplash.com/photo-1615368144592-6a8d1dfc9f5c",
                            Name = "Perfume Oils",
                            Price = 35m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 7,
                            Category = "Clothing",
                            Description = "Traditional Egyptian garments in vibrant colors.",
                            ImageUrl = "https://images.unsplash.com/photo-1551232864-3f0890e580d9",
                            Name = "Cotton Galabeyas",
                            Price = 55m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 8,
                            Category = "Home Decor",
                            Description = "Hand-hammered copper plates and bowls with Egyptian patterns.",
                            ImageUrl = "https://images.unsplash.com/photo-1584735422189-fbd9e34104b2",
                            Name = "Copper Tableware",
                            Price = 75m,
                            StockQuantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
