// <auto-generated />
using EgyptTour.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTour.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510152855_RecreateDatabase")]
    partial class RecreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptTour.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Artifacts",
                            Description = "Authentic Egyptian papyrus artwork featuring ancient hieroglyphics and scenes from Egyptian mythology.",
                            ImageUrl = "/images/products/papyrus-art.jpg",
                            Name = "Handcrafted Papyrus Art",
                            Price = 45.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Textiles",
                            Description = "Luxurious hand-woven scarf made from premium Egyptian cotton, featuring traditional patterns.",
                            ImageUrl = "/images/products/cotton-scarf.jpg",
                            Name = "Egyptian Cotton Scarf",
                            Price = 35.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            Category = "Artwork",
                            Description = "Authentic Egyptian papyrus paintings with ancient motifs.",
                            ImageUrl = "https://images.unsplash.com/photo-1565992441121-4367c2967103",
                            Name = "Handcrafted Papyrus Art",
                            Price = 45m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Category = "Artifacts",
                            Description = "Hand-carved alabaster vase with traditional Egyptian motifs, perfect for home decoration.",
                            ImageUrl = "/images/products/alabaster-vase.jpg",
                            Name = "Alabaster Vase",
                            Price = 75.00m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 5,
                            Category = "Food",
                            Description = "Collection of authentic Egyptian spices and herbs, perfect for traditional cooking.",
                            ImageUrl = "/images/products/spice-set.jpg",
                            Name = "Egyptian Spice Set",
                            Price = 25.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 6,
                            Category = "Textiles",
                            Description = "Traditional Egyptian handwoven basket made from natural materials.",
                            ImageUrl = "/images/products/basket.jpg",
                            Name = "Handwoven Basket",
                            Price = 30.00m,
                            StockQuantity = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
